version: '3.8'
services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=torneo-tenis.c9kgmc28qg76.us-east-2.rds.amazonaws.com
      - DB_PORT=3306
      - DB_DATABASE=torneo-tenis
      - DB_USERNAME=admin
      - DB_PASSWORD=G30p4g0s_99
    depends_on:
      - web

  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
